services:
  mongo:
    image: mongo:7
    container_name: chimu-mongo
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - chimu-mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chimu

volumes:
  chimu-mongo-data:
